name: ws

on: 
  workflow_dispatch:
  push:
    branches:
    - devel
    - stage
    - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'


      - run: npm install
        name: Dependencies Installation
      
      - run: npm run lint
        name: lint
      
      - run: CI=true npm run test
        name: test

      - run: npm run build
        name: build
      
      - name: upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
  
  
  deploy:
    needs: build 
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4
        name: just checkout

      - name: Download the artifact
        uses: actions/download-artifact@v3  
        with:
          name: build-artifact
          path: build
      
      - name: Get creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      
      - name: deploy
        run: aws s3 sync build s3://${{vars.BUCKET_PREFIX}}-${{github.ref_name}} --delete
      

        